module.exports = {
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  purge: { enabled: true, content: ["./example/index.html"] },
  theme: {
    screens: {
      dt: "780px",
      sm: { max: "425px" },
    },
    colors: {
      primary: {
        light: "#0B2E5B",
        main: "#667eea",
        dark: "#C8602B",
      },
      secondary: "#22394D",
      text: {
        primary: "#0B0C0C",
        secondary: "#505A5F",
      },
      link: {
        normal: "#1D70B8",
        hover: "#003078",
      },
      border: "#D6D5D4",
      inputBorder: "#464646",
      "input-border": "#464646",
      focus: "#667eea",
      error: "#D83A2F",
      success: "#2E9E8F",
      black: "#000000",
      grey: {
        dark: "#9E9E9E",
        mid: "#EEEEEE",
        light: "#FAFAFA",
        bg: "#E3E3E3",
      },
      white: "#FFFFFF",
    },
    fontFamily: {
      sans: ["Roboto", "sans-serif"],
      rc: ['"Roboto Condensed"', "sans-serif"],
    },
    fontSize: {
      "heading-xl-dt": ["3rem", "3.5rem"],
      "heading-xl": ["2rem", "2.5rem"],
      "heading-l-dt": ["2.25rem", "2.5rem"],
      "heading-l": ["1.5rem", "2rem"],
      "heading-m-dt": ["1.5rem", "2rem"],
      "heading-m": ["1.125rem", "1.75rem"],
      "heading-s": ["1rem", "1.5rem"],
      "caption-xl-dt": ["1.6875rem", "2rem"],
      "caption-xl": ["1.125rem", "1.625rem"],
      "caption-l-dt": ["1.5rem", "1.75rem"],
      "caption-l": ["1.125rem", "1.3125rem"],
      "caption-m-dt": ["1.1875rem", "1.4375rem"],
      "caption-m": ["1rem", "1.1875rem"],
      "form-field": ["1rem", "1.25rem"],
      "body-l-dt": ["1.1875rem", "1.75rem"],
      "body-l": ["1rem", "1.5rem"],
      "body-s-dt": ["1rem", "1.5rem"],
      "body-s": ["0.875rem", "1rem"],
      legend: ["1.1875rem", "1.4375rem"],
      link: ["1rem", "1.5rem"],
      "text-btn": ["1rem", "1.5rem"],
    },
    fontWeight: {
      regular: 400,
      medium: 500,
      bold: 700,
    },
    padding: {
      sm: "8px",
      md: "16px",
      lg: "24px",
      xl: "36px",
    },
    margin: {
      xs: "4px",
      sm: "8px",
      md: "16px",
      lg: "24px",
      xl: "64px",
    },
    borderWidth: {
      default: "1px",
      0: "0",
      2: "1px",
      4: "4px",
      10: "10px",
    },
    boderRadius: {
      default: "5px",
      0: "0",
      2: "2px",
    },
    boxShadow: {
      card: "0 1px 2px 0 rgba(0, 0, 0, 0.16)",
      radiobtn: "0 0 0 5px #667eea",
    },
    inset: {
      0: 0,
      6: "6px",
      10: "10px",
    },
    extend: {
      backgroundImage: {
        "success-gradient": "linear-gradient(135deg, #22c55e, #15803d)",
        "error-gradient": "linear-gradient(135deg, #ef4444, #b91c1c)",
      },
    },
    digitv2: {
      lightTheme: {
        primary: "#667eea",
        "text-color-primary": "#0B0C0C",
        "text-color-secondary": "#505A5F",
        "text-color-disabled": "#B1B4B6",
        background: "#EEEEEE",
        paper: "#FFFFFF",
        "paper-secondary": "#FAFAFA",
        divider: "#D6D5D4",
        "header-sidenav": "#0B4B66",
        "input-border": "#505A5F",
        "primary-bg": "#FEEFE7",
      },
      alert: {
        error: "#D83A2F",
        "error-bg": "#EFC7C1",
        success: "#2E9E8F",
        "success-bg": "#BAD6C9",
        info: "#3498DB",
        "info-bg": "#C7E0F1",
      },
      chart: {
        "chart-1": "#048BD0",
        "chart-1-gradient": "#048BD0",
        "chart-2": "#FBC02D",
        "chart-2-gradient": "#FBC02D",
        "chart-3": "#8E29BF",
        "chart-4": "#EA8A3B",
        "chart-5": "#0BABDE",
      },
      fontSize: {
        "heading-xl": {
          mobile: "2rem",
          tablet: "2.25rem",
          desktop: "2.5rem",
        },
        "heading-l": {
          mobile: "1.5rem",
          tablet: "1.75rem",
          desktop: "2rem",
        },
        "heading-m": {
          mobile: "1.25rem",
          tablet: "1.375rem",
          desktop: "1.5rem",
        },
        "heading-s": {
          mobile: "1rem",
          tablet: "1rem",
          desktop: "1rem",
        },
        "heading-xs": {
          mobile: "0.75rem",
        },
        "caption-l": {
          mobile: "1.5rem",
          tablet: "1.75rem",
          desktop: "1.75rem",
        },
        "caption-m": {
          mobile: "1.25rem",
          tablet: "1.5rem",
          desktop: "1.5rem",
        },
        "caption-s": {
          mobile: "1rem",
          tablet: "1.25rem",
          desktop: "1.25rem",
        },
        "body-l": {
          mobile: "1rem",
          tablet: "1.25rem",
          desktop: "1.25rem",
        },
        "body-s": {
          mobile: "0.875rem",
          tablet: "1rem",
          desktop: "1rem",
        },
        "body-xs": {
          mobile: "0.75rem",
          tablet: "0.875rem",
          desktop: "0.875rem",
        },
        label: {
          mobile: "1rem",
          tablet: "1rem",
          desktop: "1rem",
        },
        link: {
          mobile: "1rem",
          tablet: "1rem",
          desktop: "1rem",
        },
      },
      fontFamily: {
        sans: ["Roboto"],
        rc: ['"Roboto Condensed"'],
      },
      fontStyle: {
        normal: "normal",
        italic: "italic",
      },
      textDecorationLine: {
        underline: "underline",
      },
      fontWeight: {
        regular: 400,
        medium: 500,
        bold: 700,
      },
      lineHeight: {
        "line-height-body-l": { mobile: "1.5rem", tablet: "1.75rem", desktop: "1.75rem" },
        "line-height-body-s": { mobile: "1.0938rem", tablet: "1.5rem", desktop: "1.5rem" },
        "line-height-body-xs": { mobile: "1.125rem", tablet: "1.5rem", desktop: "1.5rem" },
        normal: "normal",
      },
      screens: {
        mobile: "400px",
        tablet: "768px",
        desktop: "1024px",
      },
    },
  },
  variants: {},
  plugins: [],
};
